#!/bin/bash
if [ "$(id -u)" -eq 0 ]; then
    echo "This script should not be run as root."
    exit 1
fi

echo "  ***** Now Installing Scripts *****  "
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install jq git wget telnet gh

echo "  ***** Please follow these steps to log into GitHub *****  "
gh config set -h github.com git_protocol ssh
gh auth login

mkdir -p ~/repos && cd ~/repos || exit
gh clone medisafe/devops-tools.git
# link repo dir to local system
ln -s ~/repos/devops-tools/scripts ~/.
# fix path to include $HOME/scripts dir

# shellcheck disable=SC2016
if ! grep -qxF 'export PATH="$HOME/scripts:$PATH"' ~/.zshrc; then sed -i '' '/export PATH/s/:$HOME\/scripts//;/export PATH/s/"$HOME"\/scripts//' ~/.zshrc && echo 'export PATH="$HOME/scripts:$PATH"' >> ~/.zshrc; fi
echo "  ***** All Done Installing Scripts *****  "
